#!/usr/bin/env bash
trap 'rm -f ~/projects/MultiworldGG/output/apworlds/papa-louie-2.apworld; exit 0' TERM
if test -n "$VERSION"; then
  sed -i 's/"world_version": .*,/"world_version": "'"$VERSION"'.0.0",/' archipelago.json
fi
python3.13 make_apworlds.py papa-louie-2 &>/dev/null
generate-global-tracker-data papa-louie-2 &>/dev/null
echo ~/projects/MultiworldGG/output/apworlds/papa-louie-2.apworld

while :; do
  sleep 1
done
